### ISSUE TITLE
Support using external event loop for servers

### ISSUE THREAD

**Issue by asuffield** [stepancheg/rust-http2#13]
I can't currently see any way to spawn asynchronous futures from within a method handler - I think I want to get hold of a tokio Remote, but it's wrapped up tightly inside httpbis. The neatest solution is probably to pass in the Core (or Handle?) when constructing the server.

Or in the more general case, we should be able to run several different servers together on one event loop.

**Comment by stepancheg** [comment]
> The neatest solution is probably to pass in the Core (or Handle?) when constructing the server.

Yes, I think passing `Handle` when constructing the server would be the right thing.

BTW, in the most cases user probably does not want to spawn spawn a future from handler, but instead resulting stream should drive the future.

**Comment by stepancheg** [comment]
`ClientBuilder` and `ServerBuilder` now have field `event_loop: Option<reactor::Remote>`. When `event_loop` field is set, it is used, and a thread with new event loop is not created.
