### ISSUE TITLE
Example server binds to TCP6 socket only, not TCP4, on OpenBSD 6.2

### ISSUE THREAD

**Issue by yarwelp** [stepancheg/rust-http2#18]
Hello, after getting the openssl and openssl-sys crates to work with ALPN on OpenBSD 6.2 which has LibreSSL 2.6.1 (https://github.com/sfackler/rust-openssl/issues/690), and also getting your tls-api-openssl crate (https://github.com/stepancheg/rust-tls-api/) to accept LibreSSL 2.6.1, I am left with only one problem.

When I do `cargo run --example server`

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/server`
started server
check it at: https://localhost:8443/
```

It turns out that the server binds to IPv6 socket only, and not to IPv4 socket.

So `curl -v --insecure https://[::1]:8443` works;

```
* Rebuilt URL to: https://[::1]:8443/
*   Trying ::1...
* TCP_NODELAY set
* Connected to ::1 (::1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=foobar.com
*  start date: Aug 14 17:00:03 2016 GMT
*  expire date: Aug 12 17:00:03 2026 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self signed certificate in certificate chain (
19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x165f2e56c000)
> GET / HTTP/2
> Host: [::1]:8443
> User-Agent: curl/7.55.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< content-type: text/html; charset=utf-8
<

<html>
    <head>
        <title>httpbis demo</title>
    </head>
    <body>
        <h3>httpbis demo</h3>
        <div>Counter: 0</div>
        <div>
            <form method='POST' action='/inc'>
                <button type='submit'>Inc</button>
            </form>
        </div>
    </body>
</html>
* Connection #0 to host ::1 left intact
```

Whereas `curl -v --insecure https://127.0.0.1:8443` does not;

```
* Rebuilt URL to: https://127.0.0.1:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8443 failed: Connection refused
* Failed to connect to 127.0.0.1 port 8443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 8443: Connection refused
```

`netstat -an | grep '\.8443'` confirms that indeed it's only bound to IPv6 socket, not IPv4;

```
tcp6         0      0  *.8443                 *.*                    LISTEN
```

**Comment by stepancheg** [comment]
Could you please check, does `TcpListener::bind("[::]:8443")` bind on IPv4? (This requires writing a simple program which I could probably write later, but cannot do right now.) It should and it does on Linux and on Windows. Probably it doesn't on OpenBSD, and if it doesn't, it is bug.

**Comment by yarwelp** [comment]
Created the following minimal program;

```rust
fn main()
{
    use std::net::{TcpListener, TcpStream};

    let listener = TcpListener::bind("[::]:8080").unwrap();

    loop {}
}
```

On OpenBSD 6.2 it binds to the IPv6 socket only as you said.

I don't have any Linux hosts available at the moment. Can you build it and run it and check with `netstat -an | grep '\.8080'` that it binds to both IPv4 and IPv6 on Linux?

**Comment by stepancheg** [comment]
I cannot check it now, but I'm 99% sure that it binds on both IPv4 and IPv6 on Linux.

However, reading rust std source code I stopped thinking it is default (because dualstack behavior is different in different implementations; cc https://github.com/rust-lang/rfcs/issues/957).

Anyway, I think it is better to patch rust-http2 to always explicitly set `IPV6_V6ONLY` to `false` (and I'm sure it should be done in rust standard library).

**Comment by yarwelp** [comment]
I installed Void Linux on a laptop of mine and tested with the same minimal program as above. It binds to tcp6 only there as well actually.

**Comment by AGWA** [comment]
Linux supports dual-stack sockets by default, so the minimal program will bind to both IPv4 and IPv6.  However, `netstat` will only show it bound to IPv6, so you have to try connecting to the port over both IPv4 and IPv6 to test this.

It's possible to disable default dual-stack sockets on Linux by writing `1` to `/proc/sys/net/ipv6/bindv6only`.

A program can override the default behavior by explicitly setting `IPV6_V6ONLY` to `0` or `1`.  Since you can't anticipate the value of `/proc/sys/net/ipv6/bindv6only`, you need to set `IPV6_V6ONLY` for predictable behavior.  Unfortunately, this has to be done before binding the socket, which is impossible with Rust's current libstd API.

OpenBSD doesn't support dual-stack sockets at all, so the minimal program will never bind to IPv4 under OpenBSD, even if were able to set `IPV6_V6ONLY` to `0` before binding.

**Comment by yarwelp** [comment]
Thanks @AGWA. Regarding OpenBSD not supporting dual-stack sockets, apparently this is by design; https://stackoverflow.com/questions/32051957/ipv6-why-are-ipv4-mapped-addresses-a-security-risk

I wonder then whether it is better to

A) run two server software instances -- one for IPv4 and one for IPv6, or

B) Run IPv6 server software only and have a userspace mechanism for accepting connections on the corresponding IPv4 socket and translating the traffic to IPv6.

Probably it would depend on the application. In my case I am working on making a single binary web server that bundles all assets, so in terms of memory usage it might be better to go with option B) for me, but does anyone know if such a program exists written in Rust because implementing said program from scratch would likely be a major undertaking I think.

**Comment by valpackett** [comment]
Why not have the one instance of server software listen on two separate sockets (v4 and v6)? I'm pretty sure nginx does exactly this.

**Comment by stepancheg** [comment]
I forgot to close the issue.

rust-http2 in master binds to both IPv4 and IPv6 (using dualstack) by default: f6518b11c3ddc065beb1d22aa284181ab5a2e962

I'm closing the issue. Please reopen if it's still relevant.
