### ISSUE TITLE
Wireshark cannot decode the generated HTTP/2

### ISSUE THREAD

**Issue by przygienda** [stepancheg/rust-http2#21]
Trying wireshark 2.5.2 here and it is not capable of decoding the produced content as HTTP/2 (and with that GRPC inside). 

I'm getting Err(Http(CodeError(Cancel)))  from fairly recent (1.5) GRPC server in C and have no means to debug it further ...

**Comment by stepancheg** [comment]
That's strange. Thanks!

**Comment by przygienda** [comment]
Yupp, trying to use the native client for a biggish project here but no beef. We have python/go/C++ clients working flawlessly against the service but native Rust GRPC client gets hammered with Err(Http(CodeError(Cancel))) albeit I see the RPC request being sent. Without wireshark no chance to analyze anything really. I can't find any other tools that would decode the pcap left by the the native RUST GRPC client so I'm stuck ...  I can provide the pcap files and even the service .proto for the first failing call ...

**Comment by stepancheg** [comment]
That might help.

Also, it would be helpful to execute rust-grpc with `RUST_LOG=debug` which produces a lot of noise.

Also, please note that there are other implementations of grpc in rust.

**Comment by przygienda** [comment]
But yours looks the best ;-) 

Debug output (nothing much, just got raw 8 every time) 

`
DEBUG 2018-03-28T02:15:25Z: tokio_reactor::background: starting background reactor
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: consuming notification queue
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 112073 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998420716701 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 79522 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 4277 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998420852179 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 43559 }
 INFO 2018-03-28T02:15:25Z: grpc::client: start call /authentication.Login/LoginCheck
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 722073 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998421648241 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 61074 }
DEBUG 2018-03-28T02:15:25Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-03-28T02:15:25Z: httpbis::client_conn: connected to 10.49.80.164:32767
DEBUG 2018-03-28T02:15:25Z: httpbis::solicit_async: send PREFACE
DEBUG 2018-03-28T02:15:25Z: httpbis::solicit_async: send frame 4
DEBUG 2018-03-28T02:15:25Z: httpbis::client_conn: handshake done
DEBUG 2018-03-28T02:15:25Z: httpbis::common::conn: sending frame HeadersFrame { flags: EndHeaders, stream_id: 1, header_fragment: b"\x83\x05 /authentication.Login/LoginCheck\x01\x0c10.49.80.164\x86\x0f\x10\x10application/grpc", stream_dep: None, padding_len: 0 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 320111633 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998741895086 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 94710 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 3021100 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998745066827 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 72252 }
DEBUG 2018-03-28T02:15:25Z: httpbis::common::conn: sending frame DataFrame { flags: 0, stream_id: 1, data: b"\0\0\0\0\x11\n\x04hide\x12\x04hide\x1a\x03T_1", padding_len: 0 }
DEBUG 2018-03-28T02:15:25Z: httpbis::common::conn: sending frame DataFrame { flags: EndStream, stream_id: 1, data: b"", padding_len: 0 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 255304 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998745429669 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 57369 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 4832 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop time - Instant { t: 2427998745523763 }
DEBUG 2018-03-28T02:15:25Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 48831 }
DEBUG 2018-03-28T02:15:25Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-03-28T02:15:25Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-03-28T02:15:26Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: received frame: Settings(SettingsFrame { settings: [InitialWindowSize(65535), MaxHeaderListSize(16384)], flags: 0 })
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: received frame: WindowUpdate(WindowUpdateFrame { stream_id: 0, increment: 983041, flags: 0 })
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: conn out window size change: 65513 -> 1048554
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 469117402 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop time - Instant { t: 2427999214717900 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 87935 }
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: send Settings(SettingsFrame { settings: [], flags: Ack })
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 205067 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop time - Instant { t: 2427999215065045 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 116529 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 8494 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop time - Instant { t: 2427999215313413 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 93504 }
DEBUG 2018-03-28T02:15:26Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: received frame: Settings(SettingsFrame { settings: [], flags: Ack })
DEBUG 2018-03-28T02:15:26Z: httpbis::common::conn: received frame: RstStream(RstStreamFrame { raw_error_code: 8, stream_id: 1, flags: 0 })
DEBUG 2018-03-28T02:15:26Z: httpbis::common::stream_map: removing stream 1, because it's closed
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 13094822 }
Err(Http(CodeError(Cancel)))
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop time - Instant { t: 2427999228544516 }
DEBUG 2018-03-28T02:15:26Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 95222 }
`

if you ping me on tonysietf@gmail.com I'll provide you the pcap file for the working with python & the failing (with grpc native) pcap file.  The rust client enveloping C libraries works BTW ...

**Comment by przygienda** [comment]
ok, closing the bug

1. wireshark is a hit-and-miss, barely beta code, don't even bother
2. the issue was that I was running 0.2.1 from crates.io and the missing te:trailers was causing CANCEL. I suggest to release ASAP 0.2.2 from master where it's fixed ... 

Otherwise very unpleasant, when I add something lilke this

            // Header::new(Bytes::from_static(b"grpc-timeout"), Bytes::from_static(b"90S")),
            // Header::new(Bytes::from_static(b"user-agent"), Bytes::from_static(b"grpc-rust")),

the header seems to get out corrupted. Generally the headers are very barebone, no encodings, compressions and so on given ... 

I'll report further ;-)
