### ISSUE TITLE
futures 0.2 broke that 

### ISSUE THREAD

**Issue by przygienda** [stepancheg/rust-http2#24]
due to dependency on tokio-tls-api which seems an abandoned crate by now that did not assert that it depends on futures="0.1"

**Comment by przygienda** [comment]
and much much worse tokio-tls-api is a mysterious crate with wrong authors and nuked repo ?

**Comment by przygienda** [comment]
found the rust-tls-api (largely by chance), forked, fixed, generated a pull request ...

**Comment by stepancheg** [comment]
Thank you!
