### ISSUE TITLE
Port to Async/Await

### ISSUE THREAD

**Issue by ghost** [stepancheg/rust-http2#38]
@stepancheg as I have already mentioned in [grpc-rust#164](https://github.com/stepancheg/grpc-rust/issues/164) I am wondering if it would be in the plan to port this repo to new async/await syntax together with futues 0.3.x

I am aware that tokio 0.2 is still in alpha, but I am happy to start porting small parts of the crate to the new syntax. What are your thoughts on this?

**Comment by stepancheg** [comment]
I probably don't have time to do it myself, but patches are welcome, and yes, async/await is the future.

**Comment by stepancheg** [comment]
`tls-api` crate upgraded to tokio 0.2. So now rust-http2 can be.

**Comment by stepancheg** [comment]
This crate upgraded to tokio 0.2.

So now:
* more tests needed
* convert more code to modern idioms (including `async`/`await`)
* convert grpc-rust to tokio 0.2

**Comment by stepancheg** [comment]
Done.
