### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [stepancheg/rust-http2#4]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by stepancheg** [comment]
Rust-http2 does not depend on rustc-serialize. It must one of dependencies dependency.

**Comment by dtolnay** [comment]
Ah you're right, it is coming from hpack in cbdad4fe5784cc66728fd99d9ee1f3f33e68ea05. Sorry about the confusion!
