### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by wbl** [stepancheg/rust-http2#44]
Do we really need literal frames at level debug? This is problematic when sending secret information through this library.

**Comment by stepancheg** [comment]
I agree we don't need frame contents at debug level.

**Comment by wbl** [comment]
Opened https://github.com/stepancheg/rust-http2/pull/45 for your consideration

**Comment by stepancheg** [comment]
Have a look at 9a7b842aaebf70dc9ce2155daaa26c39d5aab6c3. Is that good enough?

**Comment by wbl** [comment]
I think that does the trick. Thank you!
